/*
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class RtValidator extends AbstractRtValidator {

}
