/*
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl;


import ca.jahed.rtpoet.dsl.scoping.RtImportUriGlobalScopeProvider;
import com.google.inject.Binder;
import com.google.inject.Inject;
import org.eclipse.xtext.resource.XtextResourceSet;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RtRuntimeModule extends AbstractRtRuntimeModule {

    @Inject
    private XtextResourceSet resourceSet;

    @Override
    public void configure(Binder binder) {
        super.configure(binder);
    }

    @Override
    public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
        return RtImportUriGlobalScopeProvider.class;
    }
}