/*
 * generated by Xtext 2.25.0
 */
package ca.jahed.rtpoet.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RtStandaloneSetup extends RtStandaloneSetupGenerated {

	public static void doSetup() {
		new RtStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
